# shellcheck shell=bash
# ipsec-hub — nftables: default deny; public = IKE port(s) only; management only via tunnels.

: "${NFT_CONF:=/etc/nftables.conf}"

render_firewall() {
  local ike_ports=$IKE_PORT mgmt_tcp=22 c
  local -a boot4=() boot6=() src
  if [[ $PORT_MODE == hybrid ]]; then ike_ports="$IKE_PORT, 500"; fi
  if [[ $NODE_EXPORTER == yes ]]; then mgmt_tcp="22, 9100"; fi
  IFS=, read -ra src <<<"${SSH_BOOTSTRAP-}"
  for c in "${src[@]}"; do
    [[ -z $c ]] && continue
    if [[ $c == *:* ]]; then boot6+=("$c"); else boot4+=("$c"); fi
  done

  cat <<EOF
#!/usr/sbin/nft -f
# Generated by ipsec-hub — overwritten by 'ipsec-hub render'.
flush ruleset

table inet ipsec_hub {

  set ike_ports { type inet_service; elements = { $ike_ports }; }
  set mgmt_tcp  { type inet_service; elements = { $mgmt_tcp }; }
EOF
  if ((${#boot4[@]})); then
    printf '  set ssh_boot4 { type ipv4_addr; flags interval; elements = { %s }; }\n' "$(IFS=,; echo "${boot4[*]}")"
  else
    printf '  set ssh_boot4 { type ipv4_addr; flags interval; }\n'
  fi
  if ((${#boot6[@]})); then
    printf '  set ssh_boot6 { type ipv6_addr; flags interval; elements = { %s }; }\n' "$(IFS=,; echo "${boot6[*]}")"
  else
    printf '  set ssh_boot6 { type ipv6_addr; flags interval; }\n'
  fi

  cat <<EOF

  chain prerouting {
    type nat hook prerouting priority dstnat; policy accept;
EOF
  if [[ $PORT_MODE == hybrid ]]; then
    printf '    # Apple native clients float to 4500 after IKE_SA_INIT on 500 → hand to the NAT-T socket\n'
    printf '    iifname "%s" udp dport 4500 redirect to :%s\n' "$WAN_IF" "$IKE_PORT"
  fi
  cat <<EOF
  }

  chain postrouting {
    type nat hook postrouting priority srcnat; policy accept;
EOF
  if [[ $EGRESS == vps ]]; then printf '    oifname "%s" ip saddr %s masquerade\n' "$WAN_IF" "$POOL4"; fi
  if [[ $IPV6_MODE == nat66 ]]; then printf '    oifname "%s" ip6 saddr %s masquerade\n' "$WAN_IF" "$POOL6"; fi
  cat <<EOF
  }

  chain input {
    type filter hook input priority filter; policy drop;
    iif "lo" accept
    ct state invalid drop
    ct state { established, related } accept

    icmp type echo-request limit rate 10/second accept
    icmp type { destination-unreachable, time-exceeded, parameter-problem } accept
    icmpv6 type { nd-neighbor-solicit, nd-neighbor-advert, nd-router-solicit, nd-router-advert, packet-too-big, destination-unreachable, time-exceeded, parameter-problem } accept
    icmpv6 type echo-request limit rate 10/second accept
    iifname "$WAN_IF" udp sport 67 udp dport 68 accept
    ip6 saddr fe80::/10 udp sport 547 udp dport 546 accept

    # IKE / ESP-in-UDP — the only public service
    udp dport @ike_ports ct state new limit rate over 50/second burst 100 packets drop
    udp dport @ike_ports accept

    # management plane: only from inside the tunnels, only to mgmt0
    iifname { "xfrm-rw", "xfrm-home" } ip daddr $MGMT4 tcp dport @mgmt_tcp accept
EOF
  if [[ $SNMP_ENABLED == yes ]]; then
    printf '    iifname { "xfrm-rw", "xfrm-home" } ip daddr %s udp dport 161 accept\n' "$MGMT4"
  fi
  cat <<EOF

    # temporary bootstrap SSH (empty after 'ipsec-hub lockdown')
    iifname "$WAN_IF" ip saddr @ssh_boot4 tcp dport 22 accept
    iifname "$WAN_IF" ip6 saddr @ssh_boot6 tcp dport 22 accept

    limit rate 6/minute burst 10 packets log prefix "ipsec-hub in-drop: " level info
  }

  chain forward {
    type filter hook forward priority filter; policy drop;
    tcp flags & (syn | rst) == syn tcp option maxseg size set rt mtu
    ct state invalid drop
    ct state { established, related } accept

    iifname "xfrm-rw" oifname "xfrm-home" accept
    iifname "xfrm-home" oifname "xfrm-rw" accept
EOF
  if [[ $EGRESS == vps ]]; then
    printf '    iifname "xfrm-rw" oifname "%s" meta nfproto ipv4 accept\n' "$WAN_IF"
  fi
  if [[ $IPV6_MODE == nat66 ]]; then
    printf '    iifname "xfrm-rw" oifname "%s" meta nfproto ipv6 accept\n' "$WAN_IF"
  else
    printf '    # IPv6 is captured by the tunnel (::/0) and refused fast → no leak, quick Happy-Eyeballs fallback\n'
    printf '    iifname "xfrm-rw" meta nfproto ipv6 reject with icmpv6 type admin-prohibited\n'
  fi
  cat <<EOF

    limit rate 6/minute burst 10 packets log prefix "ipsec-hub fwd-drop: " level info
  }
}
EOF
}

# Apply with rollback: if running over SSH, require confirmation from a NEW session.
fw_apply() {
  hdr "Firewall"
  local new backup ans
  new=$(mktemp); backup=$(mktemp)
  render_firewall > "$new"
  nft -c -f "$new" || die "nft syntax check failed ($new)"
  { echo "flush ruleset"; nft list ruleset 2>/dev/null || true; } > "$backup"
  nft -f "$new"
  if [[ -n ${SSH_CONNECTION-} && $HUB_NONINTERACTIVE != 1 ]]; then
    warn "Ruleset applied. Open a NEW ssh session to confirm access, then type 'ok' here (60s, else rollback)."
    if ! read -r -t 60 -p "  confirm: " ans || [[ $ans != ok ]]; then
      nft -f "$backup"
      rm -f "$new" "$backup"
      die "no confirmation — previous ruleset restored, nothing persisted"
    fi
  fi
  install -m 0644 "$new" "$NFT_CONF"
  rm -f "$new" "$backup"
  systemctl enable nftables.service >/dev/null 2>&1 || true
  log "nftables persisted to $NFT_CONF (public: UDP/${IKE_PORT}$([[ $PORT_MODE == hybrid ]] && echo ", UDP/500, UDP/4500→$IKE_PORT"))"
}
