# shellcheck shell=bash
# ipsec-hub — monitoring: IPsec collector → node_exporter textfile + SNMPv3 extend, bound to mgmt0.

MON_KEYS=(charon_up home_up rw_ike_sas rw_child_sas home_ike_sas home_child_sas
          rw_bytes_in rw_bytes_out home_bytes_in home_bytes_out pool4_online server_cert_days)

render_collector() {
  cat <<'EOF'
#!/bin/bash
# Generated by ipsec-hub: IPsec state → /run/ipsec-hub/snmp/* and node_exporter textfile.
set -uo pipefail
PROM_DIR=/var/lib/prometheus/node-exporter
SNMP_DIR=/run/ipsec-hub/snmp
CERT=/etc/swanctl/x509/ipsec-hub-server.pem
install -d -m 0755 /run/ipsec-hub "$SNMP_DIR"

declare -A v=([charon_up]=0 [home_up]=0 [rw_ike_sas]=0 [rw_child_sas]=0 [home_ike_sas]=0 [home_child_sas]=0
              [rw_bytes_in]=0 [rw_bytes_out]=0 [home_bytes_in]=0 [home_bytes_out]=0 [pool4_online]=0 [server_cert_days]=0)

if sas=$(swanctl --list-sas 2>/dev/null); then
  v[charon_up]=1
  while read -r k val; do
    [[ $k =~ ^(rw|home)_(ike_sas|child_sas|bytes_in|bytes_out)$ ]] && v[$k]=$val
  done < <(awk '
    /^[^ ]+: #[0-9]+, /          { c=$1; sub(/:$/, "", c); if ($3 ~ /^ESTABLISHED/) ike[c]++; next }
    /^  [^ ]+: #[0-9]+, reqid /  { if ($0 ~ /INSTALLED/) child[c]++; next }
    /^ +in +/  { for (i=1;i<=NF;i++) if ($i=="bytes,") bin[c]+=$(i-1); next }
    /^ +out +/ { for (i=1;i<=NF;i++) if ($i=="bytes,") bout[c]+=$(i-1); next }
    END {
      for (k in ike)   printf "%s_ike_sas %d\n",   k, ike[k]
      for (k in child) printf "%s_child_sas %d\n", k, child[k]
      for (k in bin)   printf "%s_bytes_in %.0f\n",  k, bin[k]
      for (k in bout)  printf "%s_bytes_out %.0f\n", k, bout[k]
    }' <<<"$sas")
  pools=$(swanctl --list-pools 2>/dev/null) || pools=""
  v[pool4_online]=$(awk '$1=="rw-pool4"{print $3; exit}' <<<"$pools")
  v[pool4_online]=${v[pool4_online]:-0}
fi
(( v[home_ike_sas] > 0 && v[home_child_sas] > 0 )) && v[home_up]=1
if [[ -r $CERT ]]; then
  end=$(openssl x509 -in "$CERT" -noout -enddate | cut -d= -f2)
  v[server_cert_days]=$(( ($(date -d "$end" +%s) - $(date +%s)) / 86400 ))
fi

for k in "${!v[@]}"; do printf '%s\n' "${v[$k]}" > "$SNMP_DIR/$k"; done

[[ -d $PROM_DIR ]] || exit 0
tmp=$(mktemp "$PROM_DIR/.ipsec_hub.XXXXXX")
{
  echo "# HELP ipsec_hub_up charon reachable over VICI"
  echo "# TYPE ipsec_hub_up gauge"
  echo "ipsec_hub_up ${v[charon_up]}"
  echo "# HELP ipsec_hub_ike_sas Established IKE SAs"
  echo "# TYPE ipsec_hub_ike_sas gauge"
  echo "ipsec_hub_ike_sas{conn=\"rw\"} ${v[rw_ike_sas]}"
  echo "ipsec_hub_ike_sas{conn=\"home\"} ${v[home_ike_sas]}"
  echo "# HELP ipsec_hub_child_sas Installed CHILD SAs"
  echo "# TYPE ipsec_hub_child_sas gauge"
  echo "ipsec_hub_child_sas{conn=\"rw\"} ${v[rw_child_sas]}"
  echo "ipsec_hub_child_sas{conn=\"home\"} ${v[home_child_sas]}"
  echo "# HELP ipsec_hub_sa_bytes Bytes on current CHILD SAs (resets on rekey)"
  echo "# TYPE ipsec_hub_sa_bytes gauge"
  echo "ipsec_hub_sa_bytes{conn=\"rw\",dir=\"in\"} ${v[rw_bytes_in]}"
  echo "ipsec_hub_sa_bytes{conn=\"rw\",dir=\"out\"} ${v[rw_bytes_out]}"
  echo "ipsec_hub_sa_bytes{conn=\"home\",dir=\"in\"} ${v[home_bytes_in]}"
  echo "ipsec_hub_sa_bytes{conn=\"home\",dir=\"out\"} ${v[home_bytes_out]}"
  echo "# HELP ipsec_hub_home_up Home site IKE and CHILD SA established"
  echo "# TYPE ipsec_hub_home_up gauge"
  echo "ipsec_hub_home_up ${v[home_up]}"
  echo "# HELP ipsec_hub_pool_online Virtual IPs leased"
  echo "# TYPE ipsec_hub_pool_online gauge"
  echo "ipsec_hub_pool_online{pool=\"rw-pool4\"} ${v[pool4_online]}"
  echo "# HELP ipsec_hub_server_cert_days Days until server certificate expiry"
  echo "# TYPE ipsec_hub_server_cert_days gauge"
  echo "ipsec_hub_server_cert_days ${v[server_cert_days]}"
} > "$tmp"
chmod 0644 "$tmp"
mv -f "$tmp" "$PROM_DIR/ipsec_hub.prom"
EOF
}

render_snmp_read() {
  cat <<'EOF'
#!/bin/sh
# Generated by ipsec-hub: SNMP extend reader (runs as Debian-snmp, reads cached values only)
case "$1" in ''|*[!a-z0-9_]*) echo invalid; exit 1 ;; esac
f="/run/ipsec-hub/snmp/$1"
if [ -r "$f" ]; then cat "$f"; else echo U; fi
EOF
}

render_snmpd_conf() {
  local k
  cat <<EOF
# Generated by ipsec-hub
agentAddress udp:$MGMT4:161
sysLocation ipsec-hub $HUB_FQDN
sysContact root@$HUB_FQDN
sysServices 76
view hubview included .1
rouser -s usm $SNMP_USER priv -V hubview
disk / 10%
load 12 10 5
dontLogTCPWrappersConnects yes

# IPsec state: NET-SNMP-EXTEND-MIB::nsExtendOutput1Line."ipsecHub_<key>"
EOF
  for k in "${MON_KEYS[@]}"; do
    printf 'extend ipsecHub_%s %s/snmp-read %s\n' "$k" "$HUB_LIBEXEC" "$k"
  done
}

mon_units() {
  write_file "$HUB_LIBEXEC/collect-metrics.sh" 0755 < <(render_collector)
  write_file "$HUB_LIBEXEC/snmp-read" 0755 < <(render_snmp_read)
  write_file /etc/systemd/system/ipsec-hub-metrics.service 0644 <<EOF
[Unit]
Description=ipsec-hub IPsec metrics collector
After=$SWAN_UNIT

[Service]
Type=oneshot
ExecStart=$HUB_LIBEXEC/collect-metrics.sh
EOF
  write_file /etc/systemd/system/ipsec-hub-metrics.timer 0644 <<'EOF'
[Unit]
Description=ipsec-hub IPsec metrics every 30s

[Timer]
OnBootSec=30s
OnUnitActiveSec=30s
AccuracySec=5s

[Install]
WantedBy=timers.target
EOF
}

snmp_create_user() {
  local auth priv persist=/var/lib/snmp/snmpd.conf
  auth=$(gen_secret 32); priv=$(gen_secret 32)
  install -d -m 0700 "$HUB_SECRETS"
  ( umask 077; printf 'SNMP_USER=%s\nSNMP_AUTH_SHA256=%s\nSNMP_PRIV_AES=%s\n' "$SNMP_USER" "$auth" "$priv" > "$HUB_SECRETS/snmp.env" )
  systemctl stop snmpd.service 2>/dev/null || true
  install -d /var/lib/snmp
  touch "$persist"
  sed -i -e '/^usmUser /d' -e '/^createUser /d' "$persist"
  printf 'createUser %s SHA-256 "%s" AES "%s"\n' "$SNMP_USER" "$auth" "$priv" >> "$persist"
  log "SNMPv3 user '$SNMP_USER' (authPriv SHA-256/AES) — credentials in $HUB_SECRETS/snmp.env"
}

mon_apply() {
  hdr "Monitoring"
  mon_units
  systemctl daemon-reload
  systemctl enable --now ipsec-hub-metrics.timer >/dev/null 2>&1

  if [[ $SNMP_ENABLED == yes ]]; then
    write_file /etc/snmp/snmpd.conf 0640 < <(render_snmpd_conf)
    if getent group Debian-snmp >/dev/null; then chgrp Debian-snmp /etc/snmp/snmpd.conf; fi
    write_file /etc/systemd/system/snmpd.service.d/ipsec-hub.conf 0644 <<'EOF'
[Unit]
Wants=ipsec-hub-net.service
After=ipsec-hub-net.service
EOF
    systemctl daemon-reload
    if [[ ! -s $HUB_SECRETS/snmp.env ]]; then snmp_create_user; fi
    systemctl enable snmpd.service >/dev/null 2>&1 || true
    systemctl restart snmpd.service
    log "snmpd on udp:$MGMT4:161"
  else
    systemctl disable --now snmpd.service >/dev/null 2>&1 || true
  fi

  if [[ $NODE_EXPORTER == yes ]]; then
    write_file /etc/default/prometheus-node-exporter 0644 <<EOF
# Generated by ipsec-hub
ARGS="--web.listen-address=$MGMT4:9100 --collector.textfile.directory=/var/lib/prometheus/node-exporter"
EOF
    write_file /etc/systemd/system/prometheus-node-exporter.service.d/ipsec-hub.conf 0644 <<'EOF'
[Unit]
Wants=ipsec-hub-net.service
After=ipsec-hub-net.service
EOF
    systemctl daemon-reload
    systemctl enable prometheus-node-exporter.service >/dev/null 2>&1 || true
    systemctl restart prometheus-node-exporter.service
    log "node_exporter on http://$MGMT4:9100/metrics (ipsec_hub_* series)"
  else
    systemctl disable --now prometheus-node-exporter.service >/dev/null 2>&1 || true
  fi
  "$HUB_LIBEXEC/collect-metrics.sh" || true
}
