# shellcheck shell=bash
# ipsec-hub — addressing, detection, XFRM interfaces, policy routing, sysctl.

# XFRM interface IDs (swanctl if_id_in/out)
IFID_RW=10
IFID_SITE=20
RT_TABLE_HOME=220
TUN_MTU=1400

ip2int() { local IFS=. a b c d; read -r a b c d <<<"$1"; echo $(( (10#$a<<24) | (10#$b<<16) | (10#$c<<8) | 10#$d )); }
int2ip() { local n=$1; echo "$(( (n>>24)&255 )).$(( (n>>16)&255 )).$(( (n>>8)&255 )).$(( n&255 ))"; }

is_ipv4() {
  [[ $1 =~ ^([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$ ]] || return 1
  local i; for i in 1 2 3 4; do (( 10#${BASH_REMATCH[i]} <= 255 )) || return 1; done
}

# canonical network/prefix only (host bits must be zero)
is_cidr4() {
  [[ $1 =~ ^([0-9.]+)/([0-9]{1,2})$ ]] || return 1
  local ip=${BASH_REMATCH[1]} len=$((10#${BASH_REMATCH[2]})) n mask
  is_ipv4 "$ip" || return 1
  (( len <= 32 )) || return 1
  n=$(ip2int "$ip")
  mask=$(( len == 0 ? 0 : (0xFFFFFFFF << (32 - len)) & 0xFFFFFFFF ))
  (( (n & mask) == n ))
}

cidr4_bounds() { local n; n=$(ip2int "${1%/*}"); echo "$n $(( n + (1 << (32 - ${1#*/})) - 1 ))"; }
cidr4_overlap() {
  local a1 a2 b1 b2
  read -r a1 a2 < <(cidr4_bounds "$1"); read -r b1 b2 < <(cidr4_bounds "$2")
  (( a1 <= b2 && b1 <= a2 ))
}
cidr4_contains() { # outer inner
  local a1 a2 b1 b2
  read -r a1 a2 < <(cidr4_bounds "$1"); read -r b1 b2 < <(cidr4_bounds "$2")
  (( a1 <= b1 && b2 <= a2 ))
}

is_cidr4_list() {
  [[ -n $1 ]] || return 1
  local IFS=, c; for c in $1; do is_cidr4 "$c" || return 1; done
}
is_ipv4_list() {
  [[ -n $1 ]] || return 1
  local IFS=, c; for c in $1; do is_ipv4 "$c" || return 1; done
}
# SSH bootstrap allow-list: empty, or comma list of IPv4, IPv4/len, IPv6[/len]
is_src_list() {
  [[ -z $1 ]] && return 0
  local IFS=, c
  for c in $1; do
    is_ipv4 "$c" || is_cidr4 "$c" || [[ $c =~ ^[0-9a-fA-F:]+:[0-9a-fA-F:]*(/[0-9]{1,3})?$ ]] || return 1
  done
}
# overlay must be an RFC1918 /23 (never 100.64/10 — the home side is behind CGNAT)
is_overlay23() {
  is_cidr4 "$1" && [[ ${1#*/} == 23 ]] || return 1
  cidr4_contains 10.0.0.0/8 "$1" || cidr4_contains 172.16.0.0/12 "$1" || cidr4_contains 192.168.0.0/16 "$1"
}

derive_overlay() {
  local s; s=$(ip2int "${OVERLAY4%/*}")
  POOL4="$(int2ip "$s")/24"
  MGMT4=$(int2ip $(( s + 257 )))
}

gen_ula_pool6() { local h; h=$(openssl rand -hex 5); printf 'fd%s:%s:%s:1::/112\n' "${h:0:2}" "${h:2:4}" "${h:6:4}"; }

detect_wan_if() { ip -4 route show default 2>/dev/null | awk '{for(i=1;i<NF;i++) if($i=="dev"){print $(i+1); exit}}'; }
detect_public_ip4() { ip -4 -o addr show dev "$1" scope global 2>/dev/null | awk 'NR==1{split($4,a,"/"); print a[1]}'; }
has_global_ip6() { [[ -n $(ip -6 -o addr show dev "$1" scope global 2>/dev/null) ]]; }

check_dns() {
  local r; r=$(getent ahostsv4 "$HUB_FQDN" 2>/dev/null | awk 'NR==1{print $1}')
  if [[ -z $r ]]; then warn "$HUB_FQDN does not resolve yet — create the A record before onboarding clients"
  elif [[ $r != "$PUBLIC_IP4" ]]; then warn "$HUB_FQDN resolves to $r, not $PUBLIC_IP4"; fi
}

# Boot-time script: XFRM interfaces, mgmt dummy, routes, optional home-egress policy routing.
render_net_script() {
  local lan
  cat <<EOF
#!/bin/sh
# Generated by ipsec-hub — do not edit; run 'ipsec-hub render'.
set -eu
WAN='$WAN_IF'
modprobe xfrm_interface 2>/dev/null || true

mkif() {
  if ! ip link show "\$1" >/dev/null 2>&1; then
    # kernels >= 5.x accept XFRM interfaces without an underlying device
    ip link add "\$1" type xfrm if_id "\$2" 2>/dev/null || ip link add "\$1" type xfrm dev "\$WAN" if_id "\$2"
  fi
  ip link set "\$1" mtu $TUN_MTU up
}
mkif xfrm-rw $IFID_RW
mkif xfrm-home $IFID_SITE

# management plane: reachable only through the tunnels (enforced by nftables)
ip link show mgmt0 >/dev/null 2>&1 || ip link add mgmt0 type dummy
ip link set mgmt0 up
ip addr replace '$MGMT4/32' dev mgmt0

ip route replace '$POOL4' dev xfrm-rw
ip -6 route replace '$POOL6' dev xfrm-rw 2>/dev/null || true

ip rule del iif xfrm-rw lookup $RT_TABLE_HOME priority 1000 2>/dev/null || true
ip route flush table $RT_TABLE_HOME 2>/dev/null || true
EOF
  if [[ $HOME_ENABLED == yes ]]; then
    for lan in ${HOME_LANS//,/ }; do printf "ip route replace '%s' dev xfrm-home\n" "$lan"; done
  fi
  if [[ $EGRESS == home ]]; then
    cat <<EOF

# EGRESS=home: all client IPv4 leaves via the home site. Fail-closed: if the
# site SA is down, traffic hits xfrm-home with no SA and is dropped (no VPS egress).
ip route replace '$POOL4' dev xfrm-rw table $RT_TABLE_HOME
ip route replace default dev xfrm-home table $RT_TABLE_HOME
ip rule add iif xfrm-rw lookup $RT_TABLE_HOME priority 1000
EOF
  fi
}

render_net_unit() {
  cat <<EOF
[Unit]
Description=ipsec-hub XFRM interfaces, management address and policy routing
After=network.target
Before=strongswan.service snmpd.service prometheus-node-exporter.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=$HUB_LIBEXEC/net-up.sh

[Install]
WantedBy=multi-user.target
EOF
}

render_sysctl() {
  cat <<EOF
# Generated by ipsec-hub
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1
# forwarding=1 disables RA processing; accept_ra=2 keeps SLAAC/default route on the WAN
net/ipv6/conf/$WAN_IF/accept_ra = 2
# asymmetric paths through xfrm interfaces (home egress) need loose RPF
net.ipv4.conf.all.rp_filter = 2
net.ipv4.conf.default.rp_filter = 2
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0
net.ipv4.conf.all.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv4.tcp_syncookies = 1
net.ipv4.icmp_echo_ignore_broadcasts = 1
kernel.kptr_restrict = 2
kernel.dmesg_restrict = 1
EOF
}

net_apply() {
  hdr "Kernel & interfaces"
  write_file /etc/sysctl.d/90-ipsec-hub.conf 0644 < <(render_sysctl)
  sysctl -q --system >/dev/null 2>&1 || warn "sysctl --system reported errors (check: sysctl --system)"
  write_file "$HUB_LIBEXEC/net-up.sh" 0755 < <(render_net_script)
  write_file /etc/systemd/system/ipsec-hub-net.service 0644 < <(render_net_unit)
  systemctl daemon-reload
  systemctl enable ipsec-hub-net.service >/dev/null 2>&1
  systemctl restart ipsec-hub-net.service
  log "xfrm-rw (if_id $IFID_RW), xfrm-home (if_id $IFID_SITE), mgmt0 $MGMT4 up"
}
