# shellcheck shell=bash
# qikehub — strongSwan (charon-systemd + swanctl), route-based with XFRM interfaces.

: "${SWAN_CHARON_CONF:=/etc/strongswan.d/zz-qikehub.conf}"
: "${SWAN_CONF:=$SWANCTL_DIR/conf.d/qikehub.conf}"
SWAN_UNIT=strongswan.service

site_id() { printf '%s.sites.%s' "$HOME_NAME" "$ID_DOMAIN"; }

# Proposals
#  clients: AES-256-GCM / PRF-SHA384 / ECP-384 [+ ML-KEM-1024 via RFC 9370 ADDKE1]
#  site   : RouterOS 7 has no GCM for IKE nor ML-KEM → AES-256-CBC/SHA-384 fallback accepted
swan_set_proposals() {
  local ike="aes256gcm16-prfsha384-ecp384" esp="aes256gcm16-ecp384" pq="ke1_mlkem1024"
  case ${PQ_ACTIVE:-off} in
    require) IKE_RW="$ike-$pq";       ESP_RW="$esp-$pq" ;;
    prefer)  IKE_RW="$ike-$pq, $ike"; ESP_RW="$esp-$pq, $esp" ;;
    *)       IKE_RW="$ike";           ESP_RW="$esp" ;;
  esac
  IKE_SITE="$ike, aes256-sha384-prfsha384-ecp384"
  ESP_SITE="$esp, aes256-sha512-ecp384"
}

render_charon_conf() {
  cat <<EOF
# Generated by qikehub
charon {
    # UDP/500 is bound but firewalled unless PORT_MODE=hybrid.
    # The published port is the NAT-T socket (non-ESP marker): strongSwan-based
    # initiators on a non-500 port speak NAT-T framing from the first packet.
    port = 500
    port_nat_t = $IKE_PORT

    # routing is ours (xfrm interfaces + net-up.sh)
    install_routes = no
    install_virtual_ip = no

    send_vendor_id = no
    make_before_break = yes

    # DoS: demand cookies early, cap half-open SAs per source and globally
    cookie_threshold = 5
    block_threshold = 3
    init_limit_half_open = 200

    plugins {
        revocation {
            enable_ocsp = no
            enable_crl = yes
        }
    }
}

charon-systemd {
    journal {
        default = 1
        ike = 1
        cfg = 0
        knl = 0
    }
}
EOF
}

render_swanctl() {
  swan_set_proposals
  local dns=${CLIENT_DNS//,/, } rts
  cat <<EOF
# Generated by qikehub — overwritten by 'qikehub render'.
connections {

    rw {
        version = 2
        proposals = $IKE_RW
        pools = rw-pool4, rw-pool6
        send_cert = always
        send_certreq = yes
        encap = yes
        mobike = yes
        fragmentation = yes
        unique = replace
        dpd_delay = 60s
        rekey_time = 8h
        local {
            auth = pubkey
            certs = qikehub-server.pem
            id = $HUB_FQDN
        }
        remote {
            auth = pubkey
            id = "*@$ID_DOMAIN"
            cacerts = qikehub-ca.pem
            revocation = relaxed
        }
        children {
            rw {
                local_ts = 0.0.0.0/0, ::/0
                esp_proposals = $ESP_RW
                if_id_in = $IFID_RW
                if_id_out = $IFID_RW
                rekey_time = 1h
                dpd_action = clear
            }
        }
    }
EOF

  if [[ $HOME_ENABLED == yes ]]; then
    if [[ $EGRESS == home ]]; then rts="0.0.0.0/0"; else rts=${HOME_LANS//,/, }; fi
    cat <<EOF

    home {
        version = 2
        proposals = $IKE_SITE
        send_cert = always
        encap = yes
        mobike = no
        fragmentation = yes
        unique = replace
        dpd_delay = 30s
        rekey_time = 8h
        local {
EOF
    if [[ $HOME_AUTH == cert ]]; then
      cat <<EOF
            auth = pubkey
            certs = qikehub-server.pem
            id = $HUB_FQDN
        }
        remote {
            auth = pubkey
            id = $(site_id)
            cacerts = qikehub-ca.pem
            revocation = relaxed
        }
EOF
    else
      cat <<EOF
            auth = psk
            id = $HUB_FQDN
        }
        remote {
            auth = psk
            id = $(site_id)
        }
EOF
    fi
    cat <<EOF
        children {
            home {
                local_ts = $OVERLAY4
                remote_ts = $rts
                esp_proposals = $ESP_SITE
                if_id_in = $IFID_SITE
                if_id_out = $IFID_SITE
                rekey_time = 1h
                dpd_action = clear
                start_action = none
                close_action = none
            }
        }
    }
EOF
  fi

  cat <<EOF
}

pools {
    rw-pool4 {
        addrs = $POOL4
        dns = $dns
    }
    rw-pool6 {
        addrs = $POOL6
    }
}
EOF

  if [[ $HOME_ENABLED == yes && $HOME_AUTH == psk ]]; then
    cat <<EOF

secrets {
    ike-site {
        id-hub = $HUB_FQDN
        id-site = $(site_id)
        secret = "$(<"$HUB_SECRETS/site.psk")"
    }
}
EOF
  fi
}

swan_install_creds() {
  install -d -m 0755 "$SWANCTL_DIR/x509" "$SWANCTL_DIR/x509ca" "$SWANCTL_DIR/x509crl"
  install -d -m 0700 "$SWANCTL_DIR/private"
  install -m 0644 "$HUB_PKI/certs/ca.pem"      "$SWANCTL_DIR/x509ca/qikehub-ca.pem"
  install -m 0644 "$HUB_PKI/issued/server.pem" "$SWANCTL_DIR/x509/qikehub-server.pem"
  install -m 0600 "$HUB_PKI/private/server.key" "$SWANCTL_DIR/private/qikehub-server.key"
  install -m 0644 "$HUB_PKI/crl/crl.pem"       "$SWANCTL_DIR/x509crl/qikehub-crl.pem"
}

swan_wait_vici() {
  local i
  for i in $(seq 1 20); do
    if swanctl --stats >/dev/null 2>&1; then return 0; fi
    sleep 0.5
  done
  die "charon/VICI not reachable (journalctl -u $SWAN_UNIT)"
}

swan_pq_supported() {
  local algs; algs=$(swanctl --list-algs 2>/dev/null) || return 1
  [[ $algs == *ML_KEM_1024* ]]
}

swan_load() {
  local out
  if ! out=$(swanctl --load-all --noprompt 2>&1); then
    printf '%s\n' "$out" >&2
    die "swanctl --load-all failed"
  fi
}

swan_apply() {
  hdr "strongSwan"
  if [[ $HOME_ENABLED == yes && $HOME_AUTH == psk && ! -s $HUB_SECRETS/site.psk ]]; then
    install -d -m 0700 "$HUB_SECRETS"
    ( umask 077; gen_secret 48 > "$HUB_SECRETS/site.psk" )
  fi
  swan_install_creds

  local changed
  WF_CHANGED=0
  write_file "$SWAN_CHARON_CONF" 0644 < <(render_charon_conf)
  changed=$WF_CHANGED
  write_file "/etc/systemd/system/$SWAN_UNIT.d/qikehub.conf" 0644 <<'EOF'
[Unit]
Wants=qikehub-net.service
After=qikehub-net.service
EOF
  systemctl daemon-reload
  systemctl enable "$SWAN_UNIT" >/dev/null 2>&1 || true
  if (( changed )) || ! systemctl is-active --quiet "$SWAN_UNIT"; then
    systemctl restart "$SWAN_UNIT"
  fi
  swan_wait_vici

  PQ_ACTIVE=off
  if [[ $PQ_MODE != off ]]; then
    if swan_pq_supported; then
      PQ_ACTIVE=$PQ_MODE
      log "ML-KEM-1024 available — client key exchange: ECP-384 + ML-KEM-1024 ($PQ_MODE)"
    else
      warn "this strongSwan build has no ML-KEM — clients fall back to ECP-384 only"
    fi
  fi

  write_file "$SWAN_CONF" 0600 < <(render_swanctl)
  swan_load
  log "connections loaded: rw$([[ $HOME_ENABLED == yes ]] && echo ", home") — IKE on UDP/$IKE_PORT$([[ $PORT_MODE == hybrid ]] && echo " + 500/4500")"
}

# terminate IKE SAs whose remote identity equals ID
swan_terminate_id() {
  local id=$1 ids i
  ids=$(swanctl --list-sas 2>/dev/null | awk -v q="'" -v id="$1" '
    /^[^ ]+: #[0-9]+, / { match($0, /#[0-9]+/); cur = substr($0, RSTART + 1, RLENGTH - 1); next }
    $1 == "remote" && index($0, q id q) { print cur }') || true
  for i in $ids; do
    swanctl --terminate --ike-id "$i" --timeout 5 >/dev/null 2>&1 || true
    log "terminated IKE_SA #$i ($id)"
  done
}
