# shellcheck shell=bash
# qikehub — preflight, packages, host hardening.

preflight() {
  hdr "Preflight"
  command -v systemctl >/dev/null || die "systemd required"
  command -v apt-get >/dev/null || die "Debian/Ubuntu (apt) required"
  # shellcheck source=/dev/null
  . /etc/os-release
  case "${ID}:${VERSION_ID%%.*}" in
    debian:13|debian:14) log "$PRETTY_NAME" ;;
    ubuntu:24|ubuntu:26) warn "$PRETTY_NAME: supported; strongSwan may lack ML-KEM (PQ falls back to off)" ;;
    *) warn "untested OS: $PRETTY_NAME"; confirm "continue anyway?" || exit 1 ;;
  esac
  if ! ip xfrm state >/dev/null 2>&1; then
    die "kernel XFRM unavailable — container/OpenVZ VPS? A KVM/Xen VPS is required"
  fi
  modprobe xfrm_interface 2>/dev/null || true
  if ip link add qikehubprobe type xfrm if_id 4094 2>/dev/null; then
    ip link del qikehubprobe
  elif ip link add qikehubprobe type xfrm dev lo if_id 4094 2>/dev/null; then
    ip link del qikehubprobe
  else
    die "kernel lacks XFRM interfaces (CONFIG_XFRM_INTERFACE)"
  fi
  log "kernel $(uname -r): XFRM + xfrm interfaces OK"
}

install_packages() {
  hdr "Packages"
  local -a pkgs=(charon-systemd strongswan-swanctl strongswan-pki
                 libstrongswan-standard-plugins libstrongswan-extra-plugins
                 nftables openssl iproute2 kmod ca-certificates coreutils)
  if [[ $SNMP_ENABLED == yes ]]; then pkgs+=(snmpd); fi
  if [[ $NODE_EXPORTER == yes ]]; then pkgs+=(prometheus-node-exporter); fi
  if [[ $AUTO_UPDATES == yes ]]; then pkgs+=(unattended-upgrades); fi
  if ! dpkg -s chrony >/dev/null 2>&1; then pkgs+=(systemd-timesyncd); fi   # cert validation needs sane time
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq
  apt-get install -y -qq --no-install-recommends "${pkgs[@]}" >/dev/null
  log "installed: ${pkgs[*]}"
}

harden_ssh() {
  hdr "sshd"
  local f found=0
  for f in /root/.ssh/authorized_keys /home/*/.ssh/authorized_keys; do
    if [[ -s $f ]]; then found=1; fi
  done
  if (( ! found )); then
    warn "no authorized_keys found — NOT disabling password auth (add a key, then re-run 'qikehub render')"
    return 0
  fi
  write_file /etc/ssh/sshd_config.d/10-qikehub.conf 0644 <<'EOF'
# Generated by qikehub (sorts before cloud-init's 50-*, first match wins)
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitEmptyPasswords no
PermitRootLogin prohibit-password
MaxAuthTries 3
LoginGraceTime 20
X11Forwarding no
ClientAliveInterval 300
ClientAliveCountMax 2
EOF
  if sshd -t; then
    systemctl reload ssh.service 2>/dev/null || systemctl reload sshd.service 2>/dev/null || true
    log "sshd: key-only"
  else
    rm -f /etc/ssh/sshd_config.d/10-qikehub.conf
    warn "sshd -t failed — hardening drop-in removed"
  fi
}

auto_updates() {
  write_file /etc/apt/apt.conf.d/20auto-upgrades 0644 <<'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
EOF
  systemctl enable --now unattended-upgrades.service >/dev/null 2>&1 || true
  log "unattended security upgrades enabled"
}
